language: android
os: linux  # GNU/Linux
dist: xenial
sudo: false
android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-21
    - android-28
install:
  - echo $PWD
  - ls
before_script:
  - echo $PWD
  - ls
script:
  - echo $ANDROID_HOME
  - env
