language: android
dist: xenial
sudo: false
android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-21
    - android-28
before_script:
  - ls
script:
  - echo $ANDROID_HOME
  - env
