name: GitHub Actions
on: [push]
jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          HOGE=/dev/null
          case "${HOGE}" in
            "A") echo a;;
            '*') echo ほし;;
            *) echo default;;
          esac
          TEST=hoge ls -alF \"${{ github.workspace }}\"
          ls
      - run: echo "job.status= ${{ job.status }}"
  Windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: dir "${{ github.workspace }}"
      - run: echo job.status= ${{ job.status }}
