# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        fetch-depth: 32

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world! > yjsnpi

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.

    - name: aaaaaaaaaaaaaaaaaaaaa
      run: |
        ls -alF /usr/bin/f95
        apt list --installed | grep -E "(gfortran|flang)"
        echo test
        sudo apt {,--}purge --auto-remove gfortran
        #sudo apt install -y neofetch
        #neofetch
        alias
        [ "HOGE" ] && echo OK || echo FAIL
        [ "" ] && echo OK || echo FAIL
        whereis curl
        which curl
        git tag         YJSNPIdb8d3bd2c220b02c8c8d102b853d6032aca18a39TDKRKUJ db8d3bd2c220b02c8c8d102b853d6032aca18a39
        git push origin YJSNPIdb8d3bd2c220b02c8c8d102b853d6032aca18a39TDKRKUJ
  goisgod:
    runs-on: [ubuntu-18.04]
    needs: build
    steps:
    - name: hoge
      run: ls -alF
